name: job-matrix

on:
  push:
  
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12, 14, 16]
        exclude:
        - os: ubuntu-18.04
          node: 12
            #         include:
            #         - os: macos-latest
            #           node: 10

#     runs-on: ${{ matrix.os }}
    runs-on: self-hosted
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test

